---
version: '3.3'

services:
  server_helwor:
    build: ../server_helloworld
    container_name: server_helwor

  proxy_nginx:
    image: nginx:latest
    container_name: proxy
    ports:
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf